### ISSUE TITLE
Update pipeline failure 

### ISSUE THREAD

**Issue by samj1912** [buildpacks/profile#2]
See https://github.com/buildpacks/profile/runs/7264000321?check_suite_focus=true

cc @dmikusa-pivotal

**Comment by samj1912** [comment]
2. sounds better?

**Comment by dmikusa-pivotal** [comment]
PR #3 should resolve this.

**Comment by samj1912** [comment]
I see it still failing and I get

> Failed to add secret. Secret names must not start with GITHUB_.

when I try to add it manually
